### ISSUE TITLE
sni sniffing for domain based routing

### ISSUE THREAD

**Issue by rhjdvsgsgks** [daeuniverse/dae#110]
## What would you like us to improve

domain based routing

## Why is this needed

currently we are dns query associated with ip to get domain. it may not works if client not using standard way to query dns. afaik, some chinese bloat ware will use httpdns to query dns. and modern browser will enable doh by default. both of them will make dae not works.

in my case. dae will run on a router. and i dont have control to all client connecting it. so that i cant disable doh on every client manually.

i saw that you said its hard to write a sni sniffer in ebpf. but can we send first few bit of a packet back to userspace. do the sniffing as usual. then send result back to kernel? i know that it would be slower. so keep it as a default off option.

**Comment by yqlbu** [comment]
@rhjdvsgsgks This is a very valuable suggestion/comment. Thanks for pointing it out. We will take a closer look and see if we can come up with a desired solution for this. Cheers.

**Comment by mzz2017** [comment]
Yes, your problem should be fixed by using `domain++`. See more at <https://github.com/daeuniverse/dae/blob/main/example.dae#L70>.

Can it help you?

**Comment by mzz2017** [comment]
@rhjdvsgsgks You can try it. It does not work for direct traffic means that the traffic cannot be re-routed to proxy only if the traffic is already routed to direct by ip rules.

**Comment by mzz2017** [comment]
@rhjdvsgsgks If you want to re-route proxied traffic to direct, it can work fine.

**Comment by mzz2017** [comment]
@rhjdvsgsgks Another feature request, fwmark, is already supported. You can use it as -> proxy(mark: 0xa). But it should be fully improved by the way in another unmerged pull request  https://github.com/daeuniverse/dae/pull/80  (although it is not the main idea of this PR).

**Comment by mzz2017** [comment]
I don't mean you to go full swing to use iptables instead of ebpf as the PR describes. You can just use domain(xxx)->your_proxy_group(mark:your_mark_value) and based on the code of this PR. The mark feature is independent.

**Comment by mzz2017** [comment]
Closed due to stalled.

**Comment by Vigilans** [comment]
The problem in routing based on sniffed domain in eBPF is that in TCP the domain can only be sniffed after the handshake is completed, but eBPF must determine the route in first TCP SYN packet. User-space based proxy works because it accepts the TCP locally and start another TCP connection after determining the route.

The current domain matcher in eBPF works by reverse lookup the target IP to domain by storing the DNS result captured previously. Though it is not as good as domain sniffing, it has the benefit that non-HTTP and non-TLS TCP connection could also route using their domains, e.g. SSH connection.
