### ISSUE TITLE
`ipversion_prefer` might cause failures to access website the first time

### ISSUE THREAD

**Issue by mzz2017** [daeuniverse/dae#136]
## What happened

`ipversion_prefer` might cause failures to access website the first time.

See following image:

![image](https://github.com/daeuniverse/dae/assets/30586220/1eb84181-1a43-42c5-ad82-4a1751bb0181)

This is caused by #63. It changes behavior that responses with NX to 0.0.0.0.

**Comment by nicholas-opensource** [comment]
I started up with this idea to include a lightweight DNS tool in dae, similar to mosdns. However it turns out that both of them do a terrible job, which not a good idea. I now believe the best solution is to set up an upstream DNS forwarder with more advanced settings. Even I have abandoned this feature and found the dual stack proxy to be better than the current ipversion_prefer
I understand your point of view, you can decide whether to stay or leave this feature, sometimes it's better to keep dae simple and easy to use. Thank you for ALL YOU DO for dae. XD

**Comment by mzz2017** [comment]
@nicholas-opensource Yes. Indeed. I can reproduce this problem. Fix will be on the wat. Thanks.

**Comment by nicholas-opensource** [comment]
Youve done great things with short code to achieve powerful features. Ip version prefer is a very simple and useful feature for most scenarios. You did is one of the best I ve seen. Much appreciated~

**Comment by kunish** [comment]
@nicholas-opensource well said, rainbow fart

**Comment by troubadour-hell** [comment]
> I started up with this idea to include a lightweight DNS tool in dae, similar to mosdns. However it turns out that both of them do a terrible job, which not a good idea. I now believe the best solution is to set up an upstream DNS forwarder with more advanced settings. Even I have abandoned this feature and found the dual stack proxy to be better than the current ipversion_prefer I understand your point of view, you can decide whether to stay or leave this feature, sometimes it's better to keep dae simple and easy to use. Thank you for ALL YOU DO for dae. XD

Xianmu dual stack proxy
